SRCS	=	ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c 	\
			ft_isalpha.c ft_isascii.c ft_isdigit.c			\
			ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c 	\
			ft_memcpy.c ft_memmove.c ft_memset.c 			\
			ft_putchar_fd.c ft_putendl_fd.c 				\
			ft_putnbr_fd.c ft_putstr_fd.c ft_split.c		\
			ft_strchr.c ft_strdup.c ft_striteri.c			\
			ft_strjoin.c ft_strlcat.c ft_strlcpy.c			\
			ft_strlen.c ft_strmapi.c ft_strncmp.c			\
			ft_strnstr.c ft_strrchr.c ft_strtrim.c			\
			ft_substr.c ft_tolower.c ft_toupper.c			\
			ft_invert_str.c ft_printf.c ft_putptr_fd.c		\
			ft_putunsignednbr_fd.c ft_puthex_case_fd.c		\
			get_next_line.c ft_atof.c ft_lstnew.c 			\
			ft_lstadd_front.c ft_lstsize.c					\
			ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c	\
			ft_lstclear.c ft_lstiter.c ft_lstmap.c			\
			ft_arraylen.c ft_free_array.c

OBJS	= $(SRCS:.c=.o)

NAME	= libft.a

CC		= cc

RM 		= rm -f

CFLAGS	= -Wall -Wextra -Werror

.c.o:
			$(CC) $(CFLAGS) -c $(SRCS)

$(NAME):	$(OBJS)
			ar rcs $(NAME) $(OBJS)

all:		$(NAME)

clean:
			$(RM) $(OBJS)
			$(RM) $(BOBJS)

fclean:		clean
			$(RM) $(NAME)

re:		fclean all

.PHONY: $(NAME) all clean fclean re
